name: Deploy in AWS Lambda pipeline
on:
  push:
    branches:
      - master
jobs:
  code-quality:
    strategy:
      fail-fast: false

  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Run image
        uses: abatillo/actions-poetry@v2.0.0
        with:
          poertry-version: [1.1.8]
      - name: Install dependecies
        run: poetry install
      - name: Run black
        run: poetry run black . --check
      - name: Run isort
        run: poetry run iserto . --check-only --profile black
      - name: Run flake8
        run: poetry run flake8 .
      - name: Run bandit
        run: poetry run bandit .
      - name: Run saftey
        run: poetry run safety check
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      # sam build 
      - run: sam build --use-container

# Run Unit tests- Specify unit tests here 


# sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-hello-world --s3-bucket manual-bucket-for-api --capabilities CAPABILITY_IAM --region us-west-2
